server:
  port: 8090

spring:
  application:
    name: community
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: fzb.0226
    druid:
      initial-size: 5
      max-active: 20
      max-wait: 6000
      min-idle: 1
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  mail:
    host: smtp.qq.com # 邮箱服务器地址
    username: brantleyfan@qq.com # 用户名
    password: fxbizarhlbdebjcf # 授权码
    port: 587
  rabbitmq:
    host: localhost # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /community # rabbitmq的虚拟host
    username: community
    password: community
    publisher-confirm: true # 如果对异步消息需要回调必须设置为true
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: localhost:9200

  mvc:
    throw-exception-if-no-handler-found: true # 出现错误时, 直接抛出异常
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB

# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: t_
      id-type: auto
  type-aliases-package: com.fanzibang.community.pojo

jwt:
  secret: fanzibang
  expiration: 86400 # (一天)
  tokenHead: 'Bearer '
  tokenHeader: Authorization

oss:
  qiniu:
    access-key: 7SzE7Zod_2oDl0TeiuPRpx8wVT1bFZXBiiTXuJKw
    secret-key: SExQcq0sh5P-S2wXleeMOSogJLarYK3E68H8nnvq
    bucket: alibb-community
    url: http://img.cdn.fanzibang.xyz/

caffeine:
  discussPost:
    max-size: 15
    expire: 1440

secure:
  ignored:
    urls:
      - /**/*.ico
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /login
      - /register
      - /activation/**
      - /discussPost
      - /discussPost/list
      - /discussPost/count
      - /discussPost/{id}
      - /discussPost/delete/{id}
      - /esDiscussPost/**
      - /user/{userId}
      - /data/hotWord
      - /comment/{postId}
      - /comment/count/{postId}
      - /topic/list
      - /topic/pageList
