version: '3'
services:
  sesee-community:
    image: community:0.0.5
    container_name: sesee-community
    ports:
      - 8080:8080
    volumes:
      - /mydata/app/sesee-community/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - mysql:db # 可以用db这个域名访问mysql服务
      - elasticsearch:es # 可以用es这个域名访问elasticsearch服务
      - redis:redis # 可以用redis这个域名访问redis服务
      - rabbitmq:rabbit #可以用rabbit这个域名访问rabbitmq服务
