server:
  port: 8090

spring:
  application:
    name: community
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: fzb.0226
    druid:
      initial-size: 5
      max-active: 20
      max-wait: 6000
      min-idle: 1

#  redis:
#    host: localhost
#    database: 0
#    port: 6379
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: -1ms
#        max-idle: 8
#        min-idle: 0
#    timeout: 3000ms